Controllers/AuthController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Filters;
using MyForum.Core.Services.Interface;
using MyForum.ViewModels;
using MyForum.Core.Extensions;

namespace MyForum.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService authService;
        private readonly ITokenClaimsManager tokenClaimsManager;
        private readonly IResetPasswordService resetPasswordService;

        public AuthController(IAuthService authService, ITokenClaimsManager tokenClaimsManager,
            IResetPasswordService resetPasswordService)
        {
            this.authService = authService;
            this.tokenClaimsManager = tokenClaimsManager;
            this.resetPasswordService = resetPasswordService;
        }

        [HttpGet]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public IActionResult Login()
            => View(new LoginViewModel().WithAlert());

        [HttpGet]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public IActionResult Register()
            => View(new RegisterViewModel().WithAlert());

        [HttpGet]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public IActionResult ResetPassword()
            => View(new ResetPasswordViewModel().WithAlert());

        [HttpPost]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public async Task<IActionResult> Login(LoginViewModel viewModel)
        {
            var loggedUser = await authService.Login(viewModel.Username, viewModel.Password);

            if (loggedUser == null) return View(viewModel.WithError());
            await tokenClaimsManager.LoginWithClaims(loggedUser);

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public async Task<IActionResult> Register(RegisterViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View(viewModel);

            var registeredUser = await authService.Register(viewModel.Username, viewModel.Email, viewModel.Password);

            return registeredUser != null
                ? RedirectToAction("Login")
                    .PushAlert("Registered successfully. Check your email to confirm your account.")
                : View(viewModel.WithError());
        }

        [HttpGet]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public async Task<IActionResult> ConfirmAccount([FromQuery] ConfirmAccountViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return this.ErrorPage();

            return await authService.ConfirmAccount(viewModel.Email, viewModel.Token)
                ? (IActionResult) RedirectToAction("Login").PushAlert("Account was confirmed")
                : this.ErrorPage();
        }

        [HttpPost]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public async Task<IActionResult> SendResetPassword(ResetPasswordViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("ResetPassword", viewModel);

            await resetPasswordService.SendResetPasswordCallback(viewModel.Email, viewModel.NewPassword);

            return RedirectToAction("ResetPassword").PushAlert($"Reset token has been sent to: {viewModel.Email}");
        }

        [HttpGet]
        [ServiceFilter(typeof(OnlyAnonymousFilter))]
        public async Task<IActionResult> ConfirmResetPassword([FromQuery] ResetPasswordCallbackViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return this.ErrorPage();

            return await resetPasswordService.ResetPassword(viewModel.Email, viewModel.NewPassword, viewModel.Token)
                ? (IActionResult) RedirectToAction("Login").PushAlert("Password has been changed")
                : this.ErrorPage();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await authService.Logout();

            return RedirectToAction("Login");
        }
    }
}

Controllers/CategoryController.cs
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Extensions;
using MyForum.Core.Params;
using MyForum.Core.Services.Interface;
using MyForum.Models.Domain.Post;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IMapper mapper;
        private readonly IPostService postService;
        private readonly IProfileService profileService;

        public CategoryController(ICategoryService categoryService, IMapper mapper, IPostService postService,
        IProfileService profileService)
        {
            this.categoryService = categoryService;
            this.mapper = mapper;
            this.postService = postService;
            this.profileService = profileService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categories = await categoryService.GetCategories();
            if (categories == null)
                return this.ErrorPage();

            var mappedCategories = mapper.Map<IEnumerable<Category>, IEnumerable<CategoryViewModel>>(categories);

            return View(new CategoriesViewModel { Categories = mappedCategories });
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var category = await categoryService.GetCategory(id);
            if (category == null)
                return this.ErrorPage();

            var currentUser = await profileService.GetCurrentUser();

            var model = mapper.Map<Category, CategoryViewModel>(category);
            model.MapPosts(category.Posts.OrderByDescending(p => p.DateUpdated).ToList(), currentUser.Id);
            return View(model.WithAlert());
        }

        [HttpPost]
        public async Task<IActionResult> Details(CategoryViewModel viewModel, [FromQuery] int pageNumber = 1)
        {
            return View(viewModel.FilterPosts(await postService.GetPosts(GetPostsParams.Create
            (
                viewModel.TitleFilter,
                viewModel.Id,
                viewModel.Username,
                viewModel.SortType
            ).CurrentPage(pageNumber) as GetPostsParams), viewModel.Name));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, string categoryId)
        => await postService.DeletePost(id)
        ? RedirectToAction("Details", new { id = categoryId }).PushAlert("Post successfully deleted")
        : this.ErrorPage();
    }
}

Controllers/MainController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Extensions;
using MyForum.Core.Services.Interface;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class MainController : Controller
    {
        private readonly IPostService postService;
        private readonly ICategoryService categoryService;
        private readonly MainViewModel mainViewModel;

        public MainController(IPostService postService, ICategoryService categoryService)
        {
            this.postService = postService;
            this.categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Index()
            => View(new MainViewModel().WithAlert());


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var categories = await categoryService.GetCategories();
            return View(new CreatePostViewModel { CategoriesToSelect = categories }.WithAlert());
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Create").PushAlert("Post is valid, max title is 30 max content is 255", Core.Enums.AlertType.Error);

            var createdPost = await postService.CreatePost(viewModel.PostTitle, viewModel.Content, viewModel.CategoryId);

            if (createdPost == null)
                return RedirectToAction("Create").PushAlert("Error occured when creating a post");

            return RedirectToAction("Create").PushAlert("Post created successfully");
        }
    }
}

Controllers/ProfileController.cs
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Extensions;
using MyForum.Core.Services.Interface;
using MyForum.Models.Domain.Auth;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class ProfileController : Controller
    {
        private static ProfileViewModel profileViewModel;
        private readonly IProfileService profileService;
        private readonly IMapper mapper;
        public ProfileController(IProfileService profileService, IMapper mapper)
        {
            this.profileService = profileService;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var user = await profileService.GetCurrentUser();
            if (user == null)
                return this.ErrorPage();

            profileViewModel = (ProfileViewModel)mapper.Map<User, ProfileViewModel>(user, profileViewModel).WithAlert();

            return View(profileViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Index", profileViewModel);

            return RedirectToAction("Index").PushAlert(
                await profileService.ChangePassword(viewModel.OldPassword, viewModel.NewPassword)
                ? "Password changed successfully"
                : "Cannot change password");
        }

        [HttpPost]
        public async Task<IActionResult> ChangeEmail(ChangeEmailViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("Index", profileViewModel);

            return RedirectToAction("Index").PushAlert(
                await profileService.ChangeEmail(viewModel.NewEmail)
                ? "Email has been changed"
                : "Cannot change email");
        }
    }
}

Views/Shared/_AlertPartial.cshtml
@{
    string alertTypeClass = string.Empty;

    switch (Model?.Type)
    {
        case AlertType.Info:
            alertTypeClass = "alert-info";
            break;
        case AlertType.Success:
            alertTypeClass = "alert-success";
            break;
        case AlertType.Error:
            alertTypeClass = "alert-danger";
            break;
        default:
            alertTypeClass = "alert-info";
            break;
    }
}

@model Alert

@if (Model?.Message != null)
{
    <div id="alert" class="alert @alertTypeClass alert-dismissible fade show" role="alert">
        @Model.Message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MyForum@(ViewData["Title"] != null ? $"/{ViewData["Title"]}" : string.Empty)</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.2/lux/bootstrap.min.css"
        integrity="sha384-9+PGKSqjRdkeAU7Eu4nkJU8RFaH8ace8HGXnkiKMP9I9Te0GJ4/km3L1Z8tXigpG" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation-bar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand mx-2">MyForum</a>
        <partial name="_NavbarPartial"/>
    </nav>
    <main>
        @RenderBody()
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e7c41da766.js" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

Views/Shared/_NavbarPartial.cshtml
@using MyForum.Core.Extensions;

@if (Context.IsLoggedIn())
{
    <div class="collapse navbar-collapse" id="navigation-bar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a asp-controller="Home" asp-action="Index" class="nav-link">Home</a></li>
            <li class="nav-item"><a asp-controller="Profile" asp-action="Index" class="nav-link">Profile</a></li>
            <li class="nav-item"><a asp-controller="Category" asp-action="Index" class="nav-link">Categories</a></li>
            <li class="nav-item"><a asp-controller="Main" asp-action="Create" class="nav-link">Create</a></li>
            <li class="nav-item">
                <form asp-controller="Auth" asp-action="Logout" class="form-inline">
                    <button class="btn btn-link btn-small like-link" type="submit">Logout</button>
                </form>
            </li>
        </ul>
    </div>
}

else
{
    <div class="collapse navbar-collapse" id="navigation-bar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a asp-controller="Auth" asp-action="Login" class="nav-link">Login</a></li>
            <li class="nav-item"><a asp-controller="Auth" asp-action="Register" class="nav-link">Register</a></li>
            <li class="nav-item"><a asp-controller="Auth" asp-action="ResetPassword" class="nav-link">Reset Password</a>
            </li>
        </ul>
    </div>
}

Views/Shared/_PaginationPartial.cshtml
@model PaginationViewModel

<ul class="pagination justify-content-center">
    @if (Model.PagedList.CurrentPage > 1)
    {
        <li class="page-item">
            <button type="submit" asp-action=@Model.ActionName asp-route-pageNumber=1 class="page-link" aria-label="First">
                <span>&laquo;</span>
            </button>
        </li>

        @await Component.InvokeAsync("PaginationButton", new {actionName = Model.ActionName, pageNumber =
            Model.PagedList.CurrentPage - 1})
    }

    @await Component.InvokeAsync("PaginationButton", new {actionName = Model.ActionName, pageNumber =
        Model.PagedList.CurrentPage})

    @if (Model.PagedList.TotalPages >= Model.PagedList.CurrentPage + 1)
    {
        @await Component.InvokeAsync("PaginationButton", new {actionName = Model.ActionName, pageNumber =
            Model.PagedList.CurrentPage + 1})
    }

    @if (Model.PagedList.CurrentPage < Model.PagedList.TotalPages)
    {
        <li class="page-item">
            <button type="submit" asp-action=@Model.ActionName asp-route-pageNumber=@Model.PagedList.TotalPages
                class="page-link" aria-label="Last">
                <span>&raquo;</span>
            </button>
        </li>
    }
</ul>