Models/Domain/Post/Category.cs
using System.Collections.Generic;
using MyForum.Core.Helpers;

namespace MyForum.Models.Domain.Post
{
    public class Category
    {
        public string Id { get; set; } = Utils.Id();
        public string Name { get; set; }
        public ICollection<Post> Posts { get; set; } = new HashSet<Post>();

        public static Category Create(string name) => new Category { Name = name };
    }
}

ViewModels/CategoriesViewModel.cs
using System.Collections.Generic;
using MyForum.Models.Domain.Post;

namespace MyForum.ViewModels
{
    public class CategoriesViewModel : ErrorBaseViewModel
    {
        public IEnumerable<CategoryViewModel> Categories { get; set; }
        public CategoriesViewModel()
        {
            Title = "Categories";
        }
    }
}

ViewModels/CategoryViewModel.cs
using System.Collections.Generic;
using MyForum.Core.Enums;
using MyForum.Core.Extensions;
using MyForum.Core.Helpers;
using MyForum.Core.Params;
using MyForum.Models.Domain.Post;
using MyForum.Models.Helpers.Pagination;

namespace MyForum.ViewModels
{
    public class CategoryViewModel : ErrorBaseViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public PagedList<Post> Posts { get; set; }

        public string TitleFilter { get; set; }
        public string Username { get; set; }
        public string CurrentUserId { get; set; }
        public PostSortType SortType { get; set; }

        public CategoryViewModel FilterPosts(PagedList<Post> posts, string name)
        {
            Name = name;
            Title = name;
            Posts = posts;
            return this;
        }

        public CategoryViewModel MapPosts(ICollection<Post> posts, string currentUserId)
        {
            CurrentUserId = currentUserId;
            Posts = posts.ToPagedList<Post>(1, Constants.DefaultPageSize);
            return this;
        }
    }
}

Controllers/CategoryController.cs
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Extensions;
using MyForum.Core.Params;
using MyForum.Core.Services.Interface;
using MyForum.Models.Domain.Post;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService categoryService;
        private readonly IMapper mapper;
        private readonly IPostService postService;
        private readonly IProfileService profileService;

        public CategoryController(ICategoryService categoryService, IMapper mapper, IPostService postService,
        IProfileService profileService)
        {
            this.categoryService = categoryService;
            this.mapper = mapper;
            this.postService = postService;
            this.profileService = profileService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var categories = await categoryService.GetCategories();
            if (categories == null)
                return this.ErrorPage();

            var mappedCategories = mapper.Map<IEnumerable<Category>, IEnumerable<CategoryViewModel>>(categories);

            return View(new CategoriesViewModel { Categories = mappedCategories });
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var category = await categoryService.GetCategory(id);
            if (category == null)
                return this.ErrorPage();

            var currentUser = await profileService.GetCurrentUser();

            var model = mapper.Map<Category, CategoryViewModel>(category);
            model.MapPosts(category.Posts.OrderByDescending(p => p.DateUpdated).ToList(), currentUser.Id);
            return View(model.WithAlert());
        }

        [HttpPost]
        public async Task<IActionResult> Details(CategoryViewModel viewModel, [FromQuery] int pageNumber = 1)
        {
            return View(viewModel.FilterPosts(await postService.GetPosts(GetPostsParams.Create
            (
                viewModel.TitleFilter,
                viewModel.Id,
                viewModel.Username,
                viewModel.SortType
            ).CurrentPage(pageNumber) as GetPostsParams), viewModel.Name));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id, string categoryId)
        => await postService.DeletePost(id)
        ? RedirectToAction("Details", new { id = categoryId }).PushAlert("Post successfully deleted")
        : this.ErrorPage();
    }
}

Controllers/PostController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using MyForum.Core.Extensions;
using MyForum.Core.Services.Interface;
using MyForum.Data;
using MyForum.Models.Domain.Post;
using MyForum.Models.Helpers.Pagination;
using MyForum.ViewModels;

namespace MyForum.Controllers
{
    public class PostController : Controller
    {
        private readonly IMapper mapper;
        private readonly IDatabase database;
        private readonly IProfileService profileService;
        private readonly IAnswerService answerService;
        private readonly IPostService postService;

        public PostController(IMapper mapper, IDatabase database, IProfileService profileService,
        IAnswerService answerService, IPostService postService)
        {
            this.mapper = mapper;
            this.database = database;
            this.profileService = profileService;
            this.answerService = answerService;
            this.postService = postService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            var post = await database.PostRepository.GetPostWithAnswers(id);
            if (post == null)
                return this.ErrorPage();

            var user = await profileService.GetCurrentUser();

            var model = mapper.Map<Post, PostCardViewModel>(post);
            return View(model.WithAlert());
        }

        [HttpPost]
        public async Task<IActionResult> CreateAnswer(CreateAnswerViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Index", new { id = viewModel.PostId }).PushAlert("Answer is Valid", Core.Enums.AlertType.Error);

            var createdAnswer = await answerService.CreateAnswer(viewModel.Content, viewModel.PostId);

            if (createdAnswer == null)
                return RedirectToAction("Index", new { id = viewModel.PostId }).PushAlert("Error occured when creating a answer");

            return RedirectToAction("Index", new { id = viewModel.PostId }).PushAlert("Answer added successfully");
        }
    }
}

Views/Category/Details.cshtml
@{
    ViewData["Title"] = Model.Title;
}

@model CategoryViewModel

<div class="container text-center text-xs-center mt-3">
    <div class="row">
        <div class="col">
            <h2>Category: @Model.Name</h2>
            <hr width="50%">
        </div>
    </div>
</div>

<div class="container text-center">
    <form method="POST" class="row mt-2">
        <div class="col-md-3">
            <label asp-for="@Model.SortType">
                <select class="form-control" asp-for="@Model.SortType">
                    <option value="0">Ascending</option>
                    <option value="1">Descending</option>
                </select>
            </label>
        </div>
        <div class="col-md-2">
            <label asp-for=@Model.Username>
                <input class="form-control" type="search" asp-for=@Model.Username placeholder="Username" />
            </label>
        </div>
        <div class="col-md-2">
            <label asp-for=@Model.TitleFilter>
                <input class="form-control" type="search" asp-for=@Model.TitleFilter placeholder="Title" />
            </label>
        </div>
        <div class="col-md-3">
            <input type="hidden" asp-for=@Model.Name />
            <input type="hidden" asp-for=@Model.CurrentUserId />
            <button type="submit" class="btn btn-primary">Filter</button>
            <a asp-action="Details" class="btn btn-primary">Clear</a>
        </div>
    </form>

    <div class="row border rounded p-3 my-1">
        <div class="col-md-11 d-flex justify-content-between">
            <div class=""> Username </div>
            <div class=""> Title </div>
            <div class=""> Last Updated</div>
        </div>
    </div>

    @foreach (var post in @Model.Posts)
    {
        <div class="row border rounded p-3 my-1">
            <div class="col-md-11">
                <a asp-action="Index" asp-controller="Post" asp-route-id="@post.Id" class="d-flex justify-content-between">
                    <div class="col">
                        @post.Username
                    </div>
                    <div class="col">
                        @(post.Title.Length > 15 ? post.Title.Substring(0, 8) + "..." : post.Title)
                    </div>
                    <div class="col">
                        @post.DateUpdated.ToRelativeDate()
                    </div>
                </a>
            </div>
            @if (post.UserId == Model.CurrentUserId)
            {
                <form class="col-md-1" asp-action="Delete" asp-controller="Category" asp-route-id="@post.Id"
                    asp-route-categoryId="@Model.Id" method="POST">
                    <button type="submit" class="btn text-danger">
                        <i class="fas fa-trash"></i>
                    </button>
                </form>
            }
        </div>
    }

    <form method="POST" class="row">
        <div class="col-md-4 text-center offset-md-4">

            <input type="hidden" asp-for=@Model.SortType />
            <input type="hidden" asp-for=@Model.Id />
            <input type="hidden" asp-for=@Model.Name />
            <input type="hidden" asp-for=@Model.CurrentUserId />
            <input type="hidden" asp-for=@Model.Username />
            <input type="hidden" asp-for=@Model.TitleFilter />

            <partial name="_PaginationPartial"
                model=@(PaginationViewModel.Build<MyForum.Models.Domain.Post.Post>(Model.Posts, "Details")) />
        </div>
    </form>
</div>

Views/Category/Index.cshtml
@{
    ViewData["Title"] = Model.Title;
}

@model CategoriesViewModel

<div class="container text-center text-xs-center mt-3">
    <div class="row">
        <div class="col">
            <h2>Categories</h2>
            <hr width="50%">
        </div>
    </div>
</div>

<div class="container text-xs-center">
    <div class="row">
        @foreach (var category in Model.Categories)
        {
            <div class="col-md-4 text-center my-2">
                <a class="btn btn-outline-primary btn-lg btn-block" asp-action="Details" asp-controller="Category"
                    asp-route-id="@category.Id" asp-route-pageNumber="1">@category.Name</a>
            </div>
        }
    </div>
</div>